### PR TITLE
Abyss Overhual

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Overhauls the abyss; Textures, Displacement, Lighting. to give a truly creepy and otherworldly experience
image

### CODE REVIEW

**Comment by aHooder** [comment]
Any idea what draw distance the fog was tuned for here?

**Comment by aHooder** [comment]
This might be a pretty divisive one, but I grew used to it fairly quickly. I think it might still be worth tuning further though. The effect of the portal in the center was also interesting, but it'd be even better if the purple light stuck around (and was a little bit weaker), and an additional light was responsible for the inverted light pulse. Maybe you could attach the purple light to the orb, and place an additional world light for the pulse effect?

I think we also need to figure out what to do with the green sludge in the Abyssal Sire room

**Comment by SirFancyBacon** [comment]
image

**Comment by SirFancyBacon** [comment]
Updated imposter models for abyss obstacles 

image
image
image
image
image

**Comment by Jin-Jiyunsun** [comment]
Looks great besides a couple issues that appear in the abyssal nexus due to them sharing an area, with **normals off** this area has a noticable spotlight effect as shown in the video below, not sure what can be done about this without compromising the effect for the rest of the abyss but it looks good with **normals on** so perhaps its ok to just leave it as is;
https://github.com/117HD/RLHD/assets/37377657/218029ec-7779-492b-be4c-dd25895aa35f

this tile is missing the texture, again in the abyssal nexus;
image

and as a last suggestion it would be to remove jagex fake lighting from the tiles infront of (behind??) the font of consumption;
image

The abyssal nexus can be accessed with the fairy ring: **D I P**

**Comment by aHooder** [comment]
I'll hold off on this one for 2 more things:
- World UVs for tiles to break up the repetitiveness.
- A way to add a shallow water layer on those green sludge tiles, or alternatively a better looking replacement for them.

**Comment by aHooder** [comment]
Tile UVs are now always world coordinate based instead of local, so you can seamlessly scale and rotate them now in Overlay & Underlay like so:
```diff
	ABYSSAL_FLOOR(p -> p
		.ids(2, 121, 122)
		.area(Area.ABYSS)
		.groundMaterial(GroundMaterial.ABYSSAL_FLOOR)
+		.uvScale(3.1f)
+		.uvOrientation(33)
	),
```

I must say, I prefer the first abyssal texture for the main floor, but scaled up a bit. This might be scaled up too far, but it looks interesting imo:
image

**Comment by SirFancyBacon** [comment]
Abyssal Bile applied to Water:
image

**Comment by SirFancyBacon** [comment]
Font of Corruption baked in lighting removal and lighting improvement
image

**Comment by aHooder** [comment]
This is looking pretty good now :slightly_smiling_face:

**Pull request merged**
