### PR TITLE
Fixed possible Environment NPEs

### PR DESCRIPTION
**Pull request by ipkpjersi**
Two null checks were missing for currentEnvironment whereas there were already existing currentEnvironment null checks in this file, like for example on line 568.

### CODE REVIEW

**Comment by aHooder** [comment]
Nice find! This does indeed need null checks, but I would prefer making `currentEnvironment` always contain a valid environment instead, I think. Thanks for the PR either way :+1:

**Comment by ipkpjersi** [comment]
I think it's still worth merging as is since all the other null checks would need to be removed anyway if currentEnvironmend were changed, and it's a low risk change as it currently stands.

**Comment by aHooder** [comment]
> I think it's still worth merging as is since all the other null checks would need to be removed anyway if currentEnvironmend were changed, and it's a low risk change as it currently stands.

Yeah, I agree. I went ahead and changed it already though. Are you okay with me merging the latest changes?

**Comment by ipkpjersi** [comment]
Yep looks good to me you can merge it.

**Pull request merged**
