### PR TITLE
ground texture fixes

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Fixes for various texture issues (mostly floors blending poorly) around various places in OSRS:

### Floor pattern fixes:

betties_shop_pre
betties_shop_post

watchtower_pre
watchtower_post

### Blending correction:

aggies_floor_pre
aggies_floor_post

### Incorrectly applied textures:

varrock_east_bank_floor_pre
varrock_east_bank_floor_post

varrock_church_pre
varrock_church_post

lumb_pre
lumb_post

mages_guild_pre
mages_guild_post

fossil_hills_pre
fossil_hills_post

edge_floors_pre
edge_floors_post

edge_shop_pre
edge_shop_post

edge_bank_2_pre
image

seers_village_pre
seers_village_post

### CODE REVIEW

**Comment by xxEzri** [comment]
Most looks great to me, some adjustments:

1: Blending needs to be off for the wooden floor texture so that it doesn't bleed out of the building, this is standard elsewhere

2: Edgeville bank needs more work (more contrast on the tiles, tile texture filling the bank teller area at least)

3: I don't like the upper floor mage guild texture, if there isn't a more appropriate one then playing with the hue/saturation/lightness would probably help as the darkness and level of detail is overly eye-grabbing.

**Comment by SirFancyBacon** [comment]
1.) fixed

2.)  made adjustments:
image

3.) made adjustments:
image

**Comment by j-meds** [comment]
how come there are red tiles in the edgeville bank ?

All in all everything looks much better 👍

**Comment by xxEzri** [comment]
> 

It was that way in ~2010, with a red carpet. We're gonna poll a few things like that to see if most people want it or more 2007-like.

**Comment by SirFancyBacon** [comment]
Removed the edgeville bank overhaul; still corrected the floor in the bank.

Ready to be merged

**Comment by aHooder** [comment]
Would you be open to splitting this up further into multiple PRs? I think it would be much quicker to get things merged incrementally.

**Comment by SirFancyBacon** [comment]
> Would you be open to splitting this up further into multiple PRs? I think it would be much quicker to get things merged incrementally.

Wouldn't be opposed to this in the future; Is by region okay? Or would it be per change?

**Comment by aHooder** [comment]
> > Would you be open to splitting this up further into multiple PRs? I think it would be much quicker to get things merged incrementally.
> 
> Wouldn't be opposed to this in the future; Is by region okay? Or would it be per change?

By region is probably okay, but I think it would make sense to group only closely related/similar changes together. That way if there's some contention over a particular change, that PR can be delayed without delaying the rest of your proposed changes.

**Comment by SirFancyBacon** [comment]
Okay i can do that; would you like me to still split this PR then?

**Comment by aHooder** [comment]
If I remember correctly, basically everything that remains in this PR atm should be good to go, right? Probably not much to gain from splitting it up then.

**Comment by SirFancyBacon** [comment]
Thats what i recall but i wanted to be sure; Cool.

Once this is merged i plan to go back through and fix more things; but doing separate PRs

**Pull request merged**
