### PR TITLE
Spell lighting

### LINKED ISSUE #233: Add light source to the "Undead grasp"/Arceuus spells
It would be cool if you could add a light source to the hands in the "Undead grasp" spell/other Arceuus spells. 

[Current animation](https://streamable.com/husvnz)

### LINKED ISSUE #279: Lighting for trailblazer fire effects/animations
As the title suggests. Would be sick to see. thanks

### PR DESCRIPTION
**Pull request by Jin-Jiyunsun**
Adds lights to a bunch of spells, mainly arceuus ones some previews below.

https://github.com/117HD/RLHD/assets/37377657/790623db-bf45-4237-8b4f-df4a50c2914d

https://github.com/117HD/RLHD/assets/37377657/16fb7218-0569-47a8-9976-89d29a374d1e

https://github.com/117HD/RLHD/assets/37377657/d0210a07-f80a-4ae9-bafe-0d62c4fd3eff

https://github.com/117HD/RLHD/assets/37377657/9d663072-4418-49bf-b830-c30c4e71bb38

https://github.com/117HD/RLHD/assets/37377657/4679e612-f814-47b8-9f6a-23046d3ed060

https://github.com/117HD/RLHD/assets/37377657/3f3fc9e6-6e60-4983-8966-1832867f1a61

https://github.com/117HD/RLHD/assets/37377657/6a16a35c-8176-4561-be68-8fc662df5818

https://github.com/117HD/RLHD/assets/37377657/dd6b6d21-bc7f-46f6-b33d-47e0bdeda0c5

Closes #279 
Closes #233

### CODE REVIEW

**Comment by aHooder** [comment]
These are all looking solid to me. Let me know when/if the PR is good to go :+1:

**Comment by Jin-Jiyunsun** [comment]
https://github.com/117HD/RLHD/assets/37377657/1bbf9497-814c-4a1b-95e9-0bd9971eb3d6

https://github.com/117HD/RLHD/assets/37377657/8e31aa48-a861-4d27-be8e-4b93c77ff02c

**Comment by Jin-Jiyunsun** [comment]
tumekens shadow:

https://github.com/117HD/RLHD/assets/37377657/61e52092-efcd-4774-852d-ec041efef2f0

https://github.com/117HD/RLHD/assets/37377657/a76b061a-4dd4-4898-8048-c00fe83d7022

**Comment by Jin-Jiyunsun** [comment]
This is the last addition for now or I'll be here forever, let me know if anything looks like it needs adjusted

**Pull request merged**
