### PR TITLE
Added more texture to decoration rocks and varrock stone wall

### PR DESCRIPTION
**Pull request by j-meds**
New stone texture(STONE(263)) added. it's more subtle than the current rock textures we got. 

Added a bit more rocks to the list for example more around varrock
image

Also added more rocks that are in cave for decoration
image

Varrock walls as well
image

### CODE REVIEW

**Comment by j-meds** [comment]
> How do they look when you inherit tile color?

I mean of course it looks better just in this cave but there are literally 30,000+ of these rocks in the game next to other tile colors. SetInheritColor had bugs where it would make dark brown rocks green next to green tiles. 117 knew about this issue and was planning for a fix since it got the color from a specific corner, it should of done a mix of all the vertices in the tiles. I removed inheritColor in this case since blending works better compared to before.

**Comment by j-meds** [comment]
Pic of how most textured pile of rock decorations look. Ignore the ground decoration rocks on wall and ground, the blending from inhertTileColor is not part of the change.
image

**Comment by SirFancyBacon** [comment]
I really like those rocks, they look good!

What i did in my repo is i set some of the rocks to inherit; but others not to. Adds some nice diversity in color (imho) and also fixes the issue.

IIRC it's rocks 319, 320, and either 321 or 323

They are one of the more common outdoor rocks.

**Comment by j-meds** [comment]
> What i did in my repo is i set some of the rocks to inherit; but others not to. Adds some nice diversity in color (imho) and also fixes the issue.

Yea it does but I think at this stage it's too unpredictable since I can't go to every place and check. Some rocks get painted light teal when there isn't anything of that color in that tile or tile next to them

**Comment by aHooder** [comment]
Rebased this for you. Imo the stalagmites should get a retexture though :sweat_smile:

**Comment by j-meds** [comment]
That’s what I thought as well, Rock darkens them a lot. I’ll split when I get time, I wanted to go back on this and add stalagmite prop so we can tweak with a different texture.

**Comment by j-meds** [comment]
Any update on this PR ?

**Comment by j-meds** [comment]
Added more rocks in desert and brought in inheritTileColor #36  to more decoration rocks in desert/sides of cliffs.

BEFORE
image

AFTER
image

Added Stone texture to stairs. Blending is more noticeable in the pit.
image


@aHooder This one is ready to go when you get the time, thanks for getting #36 before this one.

**Comment by aHooder** [comment]
> Any update on this PR ?

I think we'll delay anything that adds new textures a bit longer, till we have a way to let textures override colors. Then it's probably easier to get something that looks just right rather than too dark.

> ... thanks for getting https://github.com/117HD/RLHD/pull/36 before this one.

No problem :+1: Sorry it took so long to merge.

The rock changes imo are a bit of a tossup; I think maybe inarguably, your version with inherited color feels more HD, but the bright rocks feels very old school to me. I think I'll leave it up to you guys to decide

**Comment by j-meds** [comment]
Well in the meantime, I've separated darker color rocks with a texture that doesn't darken them much. The light colored rocks seemed too bright and reflective in 117, they now blend well with the terrain. Below are the ids that got the Rock textures, feel free to move some ids to the ROCK_LIKE_OBJECT_LIGHTER which doesn't darken them much.

https://chisel.weirdgloop.org/moid/object_id.html#11190,%2011191,%2011192,%2011193,%2012578,%2012588,%2012589,12590,39742,%2039743,%2039744,%2039745,%2039746,%2039747,%2026640,%2026641

**Comment by aHooder** [comment]
This can be revisited now with the `.setOverrideBaseColor()` option introduced by #62.

**Comment by SirFancyBacon** [comment]
@j-meds any plans to revisit this? Your fixes for discolored rocks would go a long way to improving master

**Comment by j-meds** [comment]
> @j-meds any plans to revisit this? Your fixes for discolored rocks would go a long way to improving master

It's been ready. I applied a less noticeable texture for dark colored rocks as that was @aHooder hold up at that time. I don't have the time nor the motivation to continue on this or anything related to 117, if it doesn't get approved as-is feel free to clone and open your PR.

**Comment by aHooder** [comment]
> > @j-meds any plans to revisit this? Your fixes for discolored rocks would go a long way to improving master
> 
> It's been ready. I applied a less noticeable texture for dark colored rocks as that was @aHooder hold up at that time. I don't have the time nor the motivation to continue on this or anything related to 117, if it doesn't get approved as-is feel free to clone and open your PR.

I hope the hold-up isn't the cause of the lack of motivation. I'm sorry this has taken that long to merge. I'll take a look at the changes in-game and hopefully merge it once v1.2.4 is reviewed by RuneLite.

**Comment by j-meds** [comment]
> I hope the hold-up isn't the cause of the lack of motivation. I'm sorry this has taken that long to merge. I'll take a look at the changes in-game and hopefully merge it once v1.2.4 is reviewed by RuneLite.

Not at all. I haven't really been playing osrs much for the past few months. Plus I got other hobbies and priorities that come after osrs so I don't see myself playing in the future.

**Pull request merged**
