### PR TITLE
HD Stone Pattern

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Replaces the ugly stone pattern with a modified jagged_stone_tile

image

### CODE REVIEW

**Comment by aHooder** [comment]
This one I'm kind of torn on personally. I'd like to hear what others think. Here's the vanilla texture for reference:
image

**Comment by Mark7625** [comment]
I think the only issue with this texture is it looks very clean

**Comment by aHooder** [comment]
It looks a little bit too much like a floor texture to me I think, like the rock tiles aren't part of the structure.

**Comment by Mark7625** [comment]
> It looks a little bit too much like a floor texture to me I think, like the rock tiles aren't part of the structure.

yeh maybe we can make one with smaller stones

**Pull request closed without merging**
