### PR TITLE
Add update popup notice

### PR DESCRIPTION
**Pull request by aHooder**
image

### CODE REVIEW

**Comment by aHooder** [comment]
More distinguished emphasis and link following the latest commit:
image

**Comment by Mark7625** [comment]
You should edit this so it only shows to people with old model cache on

**Comment by aHooder** [comment]
> You should edit this so it only shows to people with old model cache on

We shouldn't do that in my opinion, since some people probably disabled the old cache to fix an issue it was causing with Akkha in Tombs of Amascut.

**Comment by Mark7625** [comment]
True, that's fine then I guess

**Pull request merged**
