### PR TITLE
Textured sonaphem pyramids

### PR DESCRIPTION
**Pull request by j-meds**
Before
image

After
image

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
Nice texture, which one did you use? Or is it a new one?

**Comment by Mark7625** [comment]
> Nice texture, which one did you use? Or is it a new one?

2 new textures

**Comment by Mark7625** [comment]
> Before image
> 
> After image

Hey you need to put where you got it in the liscene file so we can make sure it's copyright free

**Comment by Mark7625** [comment]
> > Nice texture, which one did you use? Or is it a new one?
> 
> New one. This site has plenty we can use for free https://3dtextures.me/
> 
> > Hey you need to put where you got it in the liscene file so we can make sure it's copyright free
> 
> Updated.

Looks fanatic wonder how this would look on the necro pyramid

**Comment by j-meds** [comment]
> Looks fanatic wonder how this would look on the necro pyramid

Unfortunately I don't have 62 agility.
@SirFancyBacon Can you access this area?

**Comment by SirFancyBacon** [comment]
> > Looks fanatic wonder how this would look on the necro pyramid
> 
> Unfortunately I don't have 62 agility. @SirFancyBacon Can you access this area?

@j-meds 
I've been sick for the past week but feeling better now; I have 72 agility so i'll check it out!
Do you know where it is by chance? lol

**Comment by j-meds** [comment]
> @j-meds I've been sick for the past week but feeling better now; I have 72 agility so i'll check it out! Do you know where it is by chance? lol

The spot is where the TOA raids are at, it's called necropolis I believe. I tried it on some blue pyramid blocks, but it didn't look good because sand is embedded in the model. I think me and @aHooder or 117 talked about a option to apply the texture based on a color hue, I think if that option were to be added it could make a lot of stuff look great. For example it would apply a brick texture only on color ranges that have a blue hue. The rest would prob be untextured.

**Comment by SirFancyBacon** [comment]
> > @j-meds I've been sick for the past week but feeling better now; I have 72 agility so i'll check it out! Do you know where it is by chance? lol
> 
> The spot is where the TOA raids are at, it's called necropolis I believe. I tried it on some blue pyramid blocks, but it didn't look good because sand is embedded in the model. I think me and @aHooder or 117 talked about a option to apply the texture based on a color hue, I think if that option were to be added it could make a lot of stuff look great. For example it would apply a brick texture only on color ranges that have a blue hue. The rest would prob be untextured.

That would fix those planks i am working on as well

**Comment by aHooder** [comment]
Textures of this resolution will have to wait I think, simply because of the file size. If you could shrink it to 256x256 this should be ready to merge :+1:

**Comment by aHooder** [comment]
While I think this does look decent, especially from further away, I don't think it really fits that these large stone slabs are made up of smaller tiles, so I think we should vote on it.

Here's how it looks from far away:
image

And here's a close-up:
image

**Comment by SirFancyBacon** [comment]
Agreed, they should be solid slabs:

https://www.istockphoto.com/photos/pyramid-giza-pyramids-close-up-egypt

**Comment by j-meds** [comment]
> Agreed, they should be solid slabs:
> 
> https://www.istockphoto.com/photos/pyramid-giza-pyramids-close-up-egypt

It looks better with the texture l, this pyramid i. That pic is not built like the in game pyramid. @aHooder I think it looks better zoomed in actually, please do a vote personally i think it looks better than no texture. Before, Bacon and mark thought it looked great.

**Comment by aHooder** [comment]
> > Agreed, they should be solid slabs:
> > https://www.istockphoto.com/photos/pyramid-giza-pyramids-close-up-egypt
> 
> It looks better with the texture, this pyramid in the pic is not built like the in game pyramid. @aHooder I think it looks better zoomed in actually, please do a vote personally i think it looks better than no texture. Before, Bacon and mark thought it looked great.

I agree, it does look better than current HD for sure. Just figured I would still point it out, though I think we are leaning towards merging this.

**Comment by SirFancyBacon** [comment]
Here is a texture i made:
image
Screenshot from 2022-10-08 22-43-40

**Comment by SirFancyBacon** [comment]
Scaled out version:
image

**Comment by aHooder** [comment]
I think @j-meds's texture fits better, even though it doesn't totally make sense. I'll merge this as that seemed to be the consensus on Discord, then we can keep iterating on this in later PRs.

**Pull request merged**
