### PR TITLE
Rellekka upgrade

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Textures wooden objects around Rellekka that are not textured; Walls, Fence gates, stiles, barricades, chairs, tables.
Textures bedrolls.
Textures Pottery Oven.
Textures anvils and furnaces.

Known Bugs: Roofs are not fully textured; I do not have 80 agility to get up there :(

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
If you get those ids I'll fix everything and make it consistent!

**Comment by aHooder** [comment]
Oh I just noticed `WOOD_GRAIN_2` gives a sharp repetitive looking edge across the roof. That's not ideal. Maybe wood grain 3 is better in the end then

**Comment by aHooder** [comment]
Maybe scaling it up could do it, yeah, though it looks kind of like more finely cut wood to my eyes. Wood grain 2 could be very nice if these seams are possible to sort out I reckon

**Comment by aHooder** [comment]
Added them now :slightly_smiling_face:

**Pull request merged**
