### PR TITLE
Docks and dockrailing

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Textures Docks around RS; Image order is before then after.

As an added bonus fences are also textured around Port Phasmatys as they use the same texture

Port Sarim:
Screenshot from 2022-08-09 22-12-44
Screenshot from 2022-08-09 22-11-55

Catherby:
Screenshot from 2022-08-09 22-22-47
Screenshot from 2022-08-09 22-21-41

Karamja:
Screenshot from 2022-08-09 22-47-42
Screenshot from 2022-08-09 22-46-28

Port Phasmatys:
Screenshot from 2022-08-09 23-04-40
Screenshot from 2022-08-09 23-06-37

### CODE REVIEW

**Comment by aHooder** [comment]
If you can find a way to match these with the original brightness, I think they would look a lot nicer :+1:

**Comment by SirFancyBacon** [comment]
> If you can find a way to match these with the original brightness, I think they would look a lot nicer +1

So playing around with it; And it seems 117HD is brighter then osrs default.

Screenshot from 2022-08-11 18-57-27
Screenshot from 2022-08-11 18-57-32
Screenshot from 2022-08-11 19-00-04

**Comment by j-meds** [comment]
I like it, I prefer the darker one which doesn't seem too dark for wood in docks. One thing that doesn't look good is when the texture doesn't flow with the seams on dock paths going east/west.
image

**Comment by aHooder** [comment]
> > If you can find a way to match these with the original brightness, I think they would look a lot nicer +1
> 
> So playing around with it; And it seems 117HD is brighter then osrs default.
> 
> Screenshot from 2022-08-11 18-57-27 Screenshot from 2022-08-11 18-57-32 Screenshot from 2022-08-11 19-00-04

This first comparison here with vanilla sells it for me :+1:

**Comment by aHooder** [comment]
I've resolved conflicts with master for you. Below is a before and after comparison of the texture applied to the docks, at default brightness:

image
image

**Comment by SirFancyBacon** [comment]
This should be ready for review

**Comment by aHooder** [comment]
This can be revisited now with the `.setOverrideBaseColor()` option introduced by #62.

**Pull request closed without merging**
