### PR TITLE
Taverley Underground Overhaul

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Overhauls the Ice Queens lair, Taverley Dungeon, and Heroes Guild Basement.

**Ice Queens Lair:**
Defines environment, overlays, underlays, objects, and lighting.

Master/PR:
image
image

**Taverley Dungeon:**

Defines ground materials, adds new ground texture variation for underground dirt caves, fixes blending issues

Master/PR:
image
image
image
image

**Heroes Guild Basement:**

Defines ground materials, adds new ground texture variation for underground dirt caves, adds lighting to dragon fire.

Master/PR:
image
image
image
image

Known issues: 
All locations:
* Walls are kinda fugly because of the shading added to the objects, a custom texture would resolve this as i can override the color; however this requires a custom texture for each location and thus textures.

Ice Queen's Lair only
* Floor is too dark, also due to the shading and the blending on tiles, for some reason i cannot override this as the brightness does not adjust with blending enabled, disabling blending makes black snow in squares around the edges of the walls. So i have chosen to accept darker floors over that. - No idea how to solve this

Despite the issues above i feel this would be a vast improvement compared to master.

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
image
Added lights

**Comment by SirFancyBacon** [comment]
This is set for review; bugs outlined in first post

**Comment by Mark7625** [comment]
Is that a new texture for the dirt its super nice

**Comment by SirFancyBacon** [comment]
Bonus: Lumbridge Swamp Caves cause i forgot to switch branches... :)

image

**Comment by SirFancyBacon** [comment]
> Is that a new texture for the dirt its super nice

It is an array of existing textures that the game is using some sort of logic to apply

**Comment by SirFancyBacon** [comment]
Motherloade Mine has the same floor as the caves i worked on. so i thought it would be a nice bonus
image

**Pull request merged**
