### PR TITLE
Draynor Bank floor

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Improves the texture on the floor with a custom texture.

Master:
image

PR:
image

### CODE REVIEW

**Comment by aHooder** [comment]
Good to go now. Let's hear what others think :+1:

**Comment by xxEzri** [comment]
Looks good to me

**Comment by aHooder** [comment]
I'm curious, did you check whether this affects the Wise Old Man blue partyhat cutscene here as well?

**Comment by SirFancyBacon** [comment]
> I'm curious, did you check whether this affects the Wise Old Man blue partyhat cutscene here as well?

I did not, can you watch that cutscene at any time?

**Comment by Mark7625** [comment]
The cutscene is in a different location so I doubt it 

This is where it happens: https://explv.github.io/?centreX=2125&centreY=4907&centreZ=0&zoom=8

**Comment by aHooder** [comment]
You should be able to view the cutscene by talking to the banker near the broken wall on the north west of the bank, then you could grab the world coordinates while watching the cutscene. Hopefully our tile override system works in instances. If not, it's not too important to include it I suppose.

**Comment by Mark7625** [comment]
DRAYNOR_BANK in areas does not include the instance add this 

	`new Rect(2127, 4911, 2137, 4903)`

https://i.imgur.com/PqjLYC9.png

**Comment by aHooder** [comment]
> DRAYNOR_BANK in areas does not include the instance add this
> 
> ```
> `new Rect(2127, 4911, 2137, 4903)`
> ```
> 
> image

It's best to verify this in-game. Those coordinates are for a 10x8 rectangle instead of  a 9x6. Presumably the house has the same dimensions in the instance, so it's probably off by a bit.

**Comment by SirFancyBacon** [comment]
Sorry on the slop above, made a mistake and wasn't sure how to fix it; It's synced with master.

I fixed the cutscene as well.

**Pull request merged**
