### PR TITLE
Water color stuff

### PR DESCRIPTION
**Pull request by xxEzri**
This patch changes the water stuff in environment manager to always use the environment's water color (defaulted to 185, 214, 255 - i.e. regular overworld water) rather than only using one when a custom color is set.

It's more failsafe than the prior approach which had a lot of weird edge cases where the water color was bad in particular zones or quests, e.g.

image

Since we're not setting the baseline water color based on the sky color any more (and don't plan to in future), i put it in its own update function which isn't called as often. Since the behavior is now the same with or without a custom color i removed the custom color bool as well. Also removed the water color settings for some environments as they are no longer needed now that they fallback to the default.

For now this removes the influence of sky color on water but for the future we have explored several ways of blending sky & water colors with fake or real reflections/effects that are much more accurate and less weird looking for edge cases. At the moment i think this is the best thing to do.

### CODE REVIEW

**Comment by xxEzri** [comment]
Should be good to go, Winter theme seems to be working fine for me

**Comment by xxEzri** [comment]
PR has introduced a bug for blood water e.g. at blood altars and vampyre zones

image

I've had a look over environmentmanager but i can't understand at the moment why it was correctly red colored before, despite different sky configs, only to break now.

Setting a blood red water color in the environment for each example works as a workaround but it's in need of a root cause fix

**Comment by xxEzri** [comment]
WaterColor 0,0,0 works as expected so maybe that explains it - those areas had dark skies and were taking the color from that. What's the best way to force all BLOOD.WATER to have the correct color globally, though?

**Comment by xxEzri** [comment]
Pushed the following:

New waterColor for true blood altar (works perfectly)

New environment for fake soul altar - pass over sky color & lighting, new water type, new waterColor

New environment for fake blood altar - pass over sky color & lighting, new waterColor

New waterColor for Arceeus - parts of it can see the above environemnts as well as ocean and has to look good for all of them.

For Arceeus, fake blood altar and soul altar i used a waterColor which doesn't add hue, but simply lighting. That lets the hue from the shader values for the water type surface color take over and has a pretty good although not perfect result. With more data for assigning water colors more specifically we could do better.

Haven't done full pics/video yet but here's a sample of what is doable:
image

Feel free to DL and take a look / take pics / suggest improvements. I didn't want to spend too many hours on this right now but it had to be at a playable state at least. It was struggling before as well.

**Comment by Mark7625** [comment]
Looks nice! The comments in the enums are kinda pointless tho, when the enum has the name

**Comment by aHooder** [comment]
Updated and included in #186.

**Pull request closed without merging**
