### PR TITLE
Add 1.1.2 update notes

### PR DESCRIPTION
**Pull request by xxEzri**
Dropping this here so we can collab

I'm thinking we should probably have a folder that has one of these for each update to document development

Direct link so that markdown formatting works properly: https://github.com/xxEzri/RLHD/blob/1.1.2-patch-notes/117HD%20v1.1.2.md

### CODE REVIEW

**Comment by xxEzri** [comment]
image
Giants' Foundry image

**Comment by Mark7625** [comment]
We already do in my panel pr with all the updates backdated also

**Comment by xxEzri** [comment]
> We already do in my panel pr with all the updates backdated also

link?

**Comment by aHooder** [comment]
Thanks! I've posted this with some modifications to the [wiki](https://github.com/117HD/RLHD/wiki/v1.1.2-Update-Changelog) :+1:

**Pull request closed without merging**
