### PR TITLE
Barbarian village houses

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Adds textures to the Barbarian Village house walls and doors.

Master / PR:
image
image

### CODE REVIEW

**Comment by aHooder** [comment]
Looks good to me :+1:

Any reason you've left out the longhall?

**Comment by SirFancyBacon** [comment]
> Looks good to me +1
> 
> Any reason you've left out the longhall?

The UV's on the roof and the pushed out sides; the current UVs stretch out on the "sides" when i make the texture vertical, so you in walls they are well hidden, but in the supports on the outside of the hall, and the corners of the roofs applying it to the long hall will make it more ugly than improved.

**Comment by SirFancyBacon** [comment]
image

**Comment by SirFancyBacon** [comment]
Mirror A and Mirror B
image
image

**Comment by aHooder** [comment]
Ah okay, I see. That's unfortunate. I guess we'll have to come back to this one when we have better tools.

**Pull request merged**
