### PR TITLE
Docks and Fences

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Textures Docks around RS; Image order is before then after.

As an added bonus fences are also textured around Port Phasmatys as they use the same texture

Port Sarim:
Screenshot from 2022-08-09 22-12-44
Screenshot from 2022-08-09 22-11-55

Karamja:

Screenshot from 2022-10-04 22-39-10
Screenshot from 2022-10-04 22-45-34
Screenshot from 2022-10-04 22-39-13

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
bug
image

**Comment by SirFancyBacon** [comment]
Phasmatys changes

master/pr
Screenshot from 2022-10-04 20-31-42
Screenshot from 2022-10-04 20-31-32

Screenshot from 2022-10-04 20-07-05
Screenshot from 2022-10-04 20-18-32

**Comment by SirFancyBacon** [comment]
Rellekka changes

master/pr:
Screenshot from 2022-10-04 20-40-21
Screenshot from 2022-10-04 20-39-10

**Comment by SirFancyBacon** [comment]
Changed the texture, updated first post with karamja; here is just a shot in Catherby
image

**Comment by aHooder** [comment]
I want to wait with this one until we have a way to rotate UVs with model orientation. Maybe I can add this tonight.

**Comment by aHooder** [comment]
Would you mind updating this PR with the new UV types introduced by #92? You can use `MODEL_XZ` to rotate UVs for GroundObjects on the docks, and `MODEL_XZ_MIRROR_A` on the diagonal joints. For reference, here's how I did it in the following image:
```json
  {
    "description": "port sarim dock planks",
    "objectIds": [ 9541 ],
    "baseMaterial": "INFERNAL_CAPE",
    "uvType": "MODEL_XZ"
  },
  {
    "description": "port sarim dock planks diagonal",
    "objectIds": [ 9542 ],
    "baseMaterial": "INFERNAL_CAPE",
    "uvType": "MODEL_XZ_MIRROR_A"
  }
  ```
image

I'm asking because it would be great if we could test #92 more before merging it, and it was written primarily to help with this PR :slightly_smiling_face:. Also, if you find anything missing or wrong with #92, please let me know!

**Comment by SirFancyBacon** [comment]
Waiting for #92

**Comment by aHooder** [comment]
I've patched this to use `MODEL_XZ` and diagonally mirrored UVs from #92 where applicable, but one final thing came to mind. Would you be open to trying this with a couple of normal maps instead of all of these textures? Something along the lines of:
```java
WOOD_GRAIN_N,
WOOD_GRAIN(WHITE, p -> p.setNormalMap(WOOD_GRAIN_N)),
```
Don't throw away what you've got though, I'm just curious whether it's feasible to do with normal maps instead. Other than that, I'm ready to merge this.

**Comment by SirFancyBacon** [comment]
The reason I have all those textures is the color override, if I don't use that then I would just have one texture and plus normals

**Comment by aHooder** [comment]
> The reason I have all those textures is the color override, if I don't use that then I would just have one texture and plus normals

Right, and it might look best with those overrides, but I was curious what it would look like with only a normal map and inherited colors. I'll give it a shot tomorrow I think :slightly_smiling_face:

**Comment by SirFancyBacon** [comment]
Ahh okay, no worries I can give it a shot when I'm home! I'll post it here and in disco

**Comment by SirFancyBacon** [comment]
You'll want to update and run around again, I added a normal and improved the texture; I don't think we will need color override now

**Comment by SirFancyBacon** [comment]
image

**Pull request merged**
