### PR TITLE
Chaos Elemental Lights

### PR DESCRIPTION
**Pull request by Jin-Jiyunsun**
Draft: Adds a subtle purple light to the Chaos Elemental and adds lights to its attacks

https://github.com/117HD/RLHD/assets/37377657/1999aebf-ba60-437e-94d3-659101ea3757

### CODE REVIEW

**Comment by Jin-Jiyunsun** [comment]
https://github.com/117HD/RLHD/assets/37377657/46a868ad-b5c3-4b08-a615-1bcc056f9c41

https://github.com/117HD/RLHD/assets/37377657/7d45c7ae-e34a-480a-957a-114781da6dc7

**Comment by aHooder** [comment]
I think I'd keep the wonky lightning effect on the chaos elemental pet, but you can probably add the purple light as well on top. The rest looks solid to me :+1:

**Comment by Jin-Jiyunsun** [comment]
https://github.com/117HD/RLHD/assets/37377657/6dfb7e6e-30f6-4996-892a-eb1779be1810
https://github.com/117HD/RLHD/assets/37377657/c4cf571a-f758-4801-90b8-ae87d71f901e

Requires a rework of the code at line 554, 555 in LightManager.java, which is beyond my ability, for both of the lights to show, as is, if this pull request is merged before that fix is in place, only the top lights on both the pet and boss will show

**Comment by aHooder** [comment]
This has been fixed in https://github.com/117HD/RLHD/commit/4a939bce9a50a9d4834b29569c1444ac8e7354f6

**Pull request merged**
