### PR TITLE
Added texture to grand exchange stone

### PR DESCRIPTION
**Pull request by j-meds**
Could have used a grungier texture but at least we got the ids mapped and now has a texture.

subtle texture to stone
image

entrance
image

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
I like it.

All of Varrock uses GRUNGE_1 for the walls; have you experimented with that at all?

**Comment by j-meds** [comment]
I mean it does look good with that one, both are good improvements. Anyways I mapped out the ids so we can swap or feel free to copy the ids and test with other textures though, I added this quickly. The new stone texture from pr #30 looks the best on this actually.

**Comment by j-meds** [comment]
@SirFancyBacon yea I swapped it out with grunge, it's better. and removed the texture for bankers since I can't texture one wall object facing west for some weird reason. image

**Comment by SirFancyBacon** [comment]
Intended or otherwise, GRUNGE_1 looks like a good stone texture.

I think the issue has something to do with object pointers.

I would leave the object references in the code, but set the material to NONE
That way once it's fixed it's a quick patch

**Pull request merged**
