### PR TITLE
Desert Treasure Questline textures

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Mostly adds textures to items and fixes ground textures for various areas touched by Desert Treasure.

Defines new material for sandy rocky areas, fixes a few bugs with grass and shadows, also defines areas missing textures

Notable changes:

- Textured 3 types of common plants
- Textured tall grass around Morytania
- Textured the inside of the Desert Treasure Pyramid
- Textured Crates and benches on the docks of Port Sarim
- Draynor Village Sewers overhaul (water is incorrect color currently)
- Digsite textures for large stones, planks, and giant vases
- Defined 4 panel styled door

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
Digsite:
image
image
image
image
image
image
image
image

**Comment by SirFancyBacon** [comment]
Crates and benchs
image
image
image
image

**Comment by SirFancyBacon** [comment]
Draynor Sewers:
image
image

**Comment by SirFancyBacon** [comment]
Plants:
image
image
image
image

**Comment by SirFancyBacon** [comment]
Desert Pyramid:
image
image

**Comment by aHooder** [comment]
Thanks for the detailed PR :slightly_smiling_face:

**Pull request merged**
