### PR TITLE
Edgeville Wooden Floors

### PR DESCRIPTION
**Pull request by SirFancyBacon**
makes the floors planks instead of tiles for the general store and random house.

Master:
image

PR:
image

### CODE REVIEW

**Comment by aHooder** [comment]
Hmm, I must say I prefer the tiles here. Maybe instead add tiles to Oziach's house as well?

**Comment by SirFancyBacon** [comment]
> Hmm, I must say I prefer the tiles here. Maybe instead add tiles to Oziach's house as well?

Tiles are what RS3/08 used.

**Comment by SirFancyBacon** [comment]
For what it's worth; I also prefer master.

Only reason i did this is for consistency's sake. Oziach's house in RS3 still has wooden planked floors.

perhaps this PR should just be scrapped? wouldn't break my heart.

**Comment by Mark7625** [comment]
I mean every house doesn't have to match, they don't irl

**Comment by aHooder** [comment]
Maybe this is best left as it is on current master then?

**Comment by SirFancyBacon** [comment]
Agreed, I'll close this pull.

**Pull request closed without merging**
