### PR TITLE
Relighting OSRS

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Tweaks lights from furnaces and Torches to add consistency as well as reduce over bright light sources.

Fire it up and run around; Most areas of lighting in the main OSRS has been redone, new areas added since 07 i haven't re-balanced yet; Waiting on reviews

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
If anyone knows of some items that are not lit that should be let me know, I am aware of #113 and will find time to start the quest and light the area

**Comment by SirFancyBacon** [comment]
With the rune alter ruins added and currently there being no way to hide the fake lights on the model. Things do not look as well as they could; If possible can we get a fix for that?

**Comment by aHooder** [comment]
Is this one perhaps worth completing in parts?

**Comment by SirFancyBacon** [comment]
Closing in favor of smaller region specific lighting changes

**Pull request closed without merging**
