### PR TITLE
Rock overhaul - Reduex

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Overhauls all of the rocks to have better UV scales as well as applies missing materials

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
This should be ready for testing and review

**Comment by SirFancyBacon** [comment]
Requires #126 for improved Corsair Cove texture

**Comment by SirFancyBacon** [comment]
Master / PR
image
image

**Comment by SirFancyBacon** [comment]
Master / PR
image
image

**Comment by aHooder** [comment]
This is a little bit too big to check properly, but from the parts I've been able to check this looks pretty good.

**Pull request merged**
