### PR TITLE
Add normals

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Adds normals to every current texture in Master;
mostly for people to download for texturing as current Normals implementation breaks things.

Test it out though

### CODE REVIEW

**Comment by aHooder** [comment]
I think we should change how materials are loaded slightly in order to make this PR work on the lowest end GPUs that we currently support. With the number of extra material slots this PR adds, we would be about 35 materials above the limit on [Intel HD Graphics 4400 & 4600 (with old drivers)](https://opengl.gpuinfo.org/listreports.php?capability=GL_MAX_UNIFORM_BLOCK_SIZE&value=16384). Incidentally I think these older drivers might not support HD anyway, so maybe it's a non-issue technically. Other than that I think I'm on board with this after checking to see that the generated texture maps look okay in-game.

**Comment by SirFancyBacon** [comment]
> I think we should change how materials are loaded slightly in order to make this PR work on the lowest end GPUs that we currently support. With the number of extra material slots this PR adds, we would be about 35 materials above the limit on [Intel HD Graphics 4400 & 4600 (with old drivers)](https://opengl.gpuinfo.org/listreports.php?capability=GL_MAX_UNIFORM_BLOCK_SIZE&value=16384). Incidentally I think these older drivers might not support HD anyway, so maybe it's a non-issue technically. Other than that I think I'm on board with this after checking to see that the generated texture maps look okay in-game.

Can someone with those chips even run with POM or Normals enabled?

**Comment by aHooder** [comment]
They could probably run with normals, but POM might be too much. We could change it so we don't need one material per texture, then we wouldn't have an issue with the uniform size limit. We'd still have the texture limit, but this PR wouldn't hit that I think.

**Comment by SirFancyBacon** [comment]
Hmm I'm not sure we can really do that, the normals need to match the textures to look correct, I could just make a "noise" texture, but I don't think it would look that great. Imho

**Comment by SirFancyBacon** [comment]
Deprecated

**Pull request closed without merging**
