### PR TITLE
Port HD to lwjgl/rlawt

### PR DESCRIPTION
**Pull request by testing-ongithub**
Changes the OpenGL backend to use lwjgl and rlawt instead of jogl.

Incorporates the changes from https://github.com/runelite/runelite/commit/f090031, https://github.com/runelite/runelite/compare/0c56435...2141304, and https://github.com/runelite/runelite/commit/b256378.

### CODE REVIEW

**Comment by Mark7625** [comment]
Everything seems to be working Great for me! Great job

**Comment by xxEzri** [comment]
Me too

**Comment by ipkpjersi** [comment]
I tested it out a bunch and it looks like it even fixed a rare bug I was encountering sometimes. This seems great!

**Comment by Mark7625** [comment]
> > I tested it out a bunch and it looks like it even fixed a rare bug I was encountering sometimes. This seems great!
> 
> which one?

Was a rare crash when loading the game like rlly rare on Linux

**Comment by ipkpjersi** [comment]
Yeah it was some weird X11 lock error on startup, super rare happened like every 1/50 times but this definitely seems to fix it so I'm even more pleased with this LWJGL port :+1:

**Comment by aHooder** [comment]
Any objections to adding a static import for `GL43C`, other than performance in IntelliJ? I don't notice a slowdown, and everything in OpenGL starts with `gl` or `GL_` anyway. Seems like a good fit. I think this is ready to merge either way.

**Comment by testing-ongithub** [comment]
My only objection is that that would introduce more of a difference between the core GPU and HD plugins, which would make porting any future changes the tiniest bit more difficult. But if you're okay with that, we can do it. Just let me know and I'll make the change 🙂

**Comment by aHooder** [comment]
Yeah, that's fine imo. The only thing I guess would be if they for instance change it to use `GL33C` in certain places, and there's somehow a name clash, but I think OpenGL is backwards compatible in that respect anyway. I have a branch you can cherry-pick from if you'd like here: https://github.com/aHooder/RLHD/commits/pr4. That also changes the `PI` constant to use `Math.PI` for initialization, since it's just the same number.

**Comment by testing-ongithub** [comment]
Updated 👍

**Pull request merged**
