### PR TITLE
Fix model cache allocation

### PR DESCRIPTION
**Pull request by aHooder**
Apparently, memory is allocated for the model cache regardless of whether caching is enabled or not... :sweat_smile: This fixes that issue, and also makes model caching options apply when changed. Some config descriptions have also been updated.

### CODE REVIEW

**Comment by Mark7625** [comment]
Looks Good, I really like the new Descriptions. Great Job!

**Comment by aHooder** [comment]
Thanks, I still need to test this on Windows to see what happens when it runs out of memory, and I think I'll also change it so it allocates in one large chunk (or a few) instead of thousands of small allocations.

**Comment by Mark7625** [comment]
What about Mac?

**Comment by aHooder** [comment]
Ideally we would test it on macOS as well, but the changes are fairly minimal, so it's really just a sanity check

**Pull request merged**
