### PR TITLE
Hd hay texture

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Replace the hay texture found on roofs with a good approximate one from ambient CG

Master/PR
image
image
image
image

### CODE REVIEW

**Comment by aHooder** [comment]
I think this one might be better with another texture. I also tried to fix an issue where displacement doesn't interact properly with shadows, so this roof now has artifacting issues with displacement. My gripes with this new material are the repeating dark patch, and the normal map possibly being too low resolution for the fine detail in the hay. Maybe it'd look nicer with a bit more blurred normals? Hard to say. If the dark patch is difficult to fix though, maybe a different texture altogether would be ideal, or just keeping the vanilla one for now.

**Comment by SirFancyBacon** [comment]
Thanks for the feed back! I 100% agree with the dark patch; tbh i was to give it to a digital artist bud of mine and see if he could correct it out; But i am rethinking with the issues on normals.. I'll use your trick about generating them from displacement map and see :)

**Comment by SirFancyBacon** [comment]
image

**Comment by SirFancyBacon** [comment]
image

**Pull request merged**
