### PR TITLE
Kharidian textures

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Textures for walls, pottery, windows, and status around the Kharidian region.

All shots are Master (top) PR (Bottom)

Al-Kharid Palace:
Screenshot from 2022-08-14 22-20-07
Screenshot from 2022-08-14 22-21-33

Al-Kharid Buildings:
Screenshot from 2022-08-14 22-24-00
Screenshot from 2022-08-14 22-23-30

Pollnicneach:
Screenshot from 2022-08-14 22-26-42
busercontent.com/11658143/184567681-9e5002af-0860-47a8-b65f-7e0195b888f3.png)

Screenshot from 2022-08-14 22-44-26
Screenshot from 2022-08-14 22-43-47

Nardah:
Screenshot from 2022-08-14 23-05-02
Screenshot from 2022-08-14 23-03-58

### CODE REVIEW

**Comment by SirFancyBacon** [comment]
Screenshot from 2022-08-15 00-06-39
Screenshot from 2022-08-15 00-06-06

**Comment by aHooder** [comment]
I would prefer a more clean marble look for all of the buildings. The other stone I think looks fairly good :+1:

**Comment by SirFancyBacon** [comment]
> I would prefer a more clean marble look for all of the buildings. The other stone I think looks fairly good +1

image

Like this?

**Comment by j-meds** [comment]
@SirFancyBacon Did you try the Rock textures? I tried it and it looked decent for a brick house near duel arena.

**Comment by SirFancyBacon** [comment]
> @SirFancyBacon Did you try the Rock textures? I tried it and it looked decent for a brick house near duel arena.
ROCK_1
Screenshot from 2022-08-21 11-43-11
ROCK_2
Screenshot from 2022-08-21 11-44-43

I'm not a fan of either

**Comment by j-meds** [comment]
Actually rock is too much for this area. yea what you proposed in the first pic looks good.

**Comment by SirFancyBacon** [comment]
rebased; Bunch of stuff i didn't change was pulled into this though..

**Comment by SirFancyBacon** [comment]
New Stucco texture; think it works out very well.

Screenshot from 2022-09-06 21-25-22
Screenshot from 2022-09-06 21-28-52
Screenshot from 2022-09-06 21-30-11
Screenshot from 2022-09-06 21-30-33

**Comment by aHooder** [comment]
Cleaned up & rebased. Let's wait till we've decided what to do with greyscale textures though :+1:

**Comment by aHooder** [comment]
This can be revisited now with the `.setOverrideBaseColor()` option introduced by #62.

**Comment by SirFancyBacon** [comment]
Also fixed by this:
Master/PR
Screenshot from 2022-09-25 19-52-00
Screenshot from 2022-09-25 19-57-34

**Comment by SirFancyBacon** [comment]
Uzer
Master/PR

Screenshot from 2022-09-25 20-17-24
Screenshot from 2022-09-25 20-18-49


Screenshot from 2022-09-25 20-40-13
Screenshot from 2022-09-25 20-40-49

**Comment by SirFancyBacon** [comment]
I'll be removing my pyramid texture in favor of #76

**Comment by SirFancyBacon** [comment]
I'm going to scrap this in favor of a rewrite. But I'll push it to the same repo

**Comment by aHooder** [comment]
> I'm going to scrap this in favor of a rewrite. But I'll push it to the same repo

It's probably less messy to submit a new PR for this then with updated screenshots.

**Pull request closed without merging**
