### PR TITLE
Cold war - Iceberg textures and ice/snow

### LINKED ISSUE #113: [BUG] Iceberg Footprints have shadows. + texture & lighting improvements request.
**Locations**
Ice Berg & Areas reached during the Cold War quest

**Describe the bug**
Footprints have shadows under them
image

**Expected behaviour:**
No shadows underneath footprints

**Iceberg Texture Feedback**
Top of ice looks like dirt instead of ice.

**Lack of lighting**
No indoor lighting 
image

**Steps to reproduce the behavior:**
Do quest: Cold War
Go to Iceberg

### PR DESCRIPTION
**Pull request by SirFancyBacon**
Textures the Ice berg region to have proper textures.
Adds lights to the Penguin Base lamps
hides shadows from footprints in the snow.

fixes #113 

image
image
image

### CODE REVIEW

**Comment by aHooder** [comment]
This looks a little bit broken:
image

Is it meant to replace the floor everywhere inside the base with ice?

**Comment by SirFancyBacon** [comment]
Oh Absolutely; I'll need to find out how that happened; thank you!

**Comment by PleaseRephraseNClarify** [comment]
> This looks a little bit broken: image
> 
> Is it meant to replace the floor everywhere inside the base with ice?

missing lighting?

Looks like the interrogation chair, projector, & music room lights are missing.

**Comment by SirFancyBacon** [comment]
> > This looks a little bit broken: image
> > Is it meant to replace the floor everywhere inside the base with ice?
> 
> My Remote Image Looks like the interrogation chair, projector, & music room lights are missing.

I didn't notice those either! Good catch!!

**Comment by SirFancyBacon** [comment]
Fixed the Penguin Base floor
image
Unfortunately we can't do real volumetric light for this:
image

But i'll see what i can do

**Comment by SirFancyBacon** [comment]
Should be ready

**Comment by aHooder** [comment]
I'm mostly on board with this one, but I'd like to try making the floor look more like regular ice. I also think we should hold back on this one until we can sync the lights up with client ticks, as that could be a pretty simple change.

**Comment by SirFancyBacon** [comment]
Sounds good to me!

**Pull request merged**
