### PR TITLE
Misc improvements/fixes

### PR DESCRIPTION
**Pull request by xxEzri**
Dropping a bunch of stuff together in here since we're modifying the same files (Area, Overlay, Underlay, Environment .javas and Lights.json) Pics and more to come.

People can run them all more easily this way and give feedback on individual changes

### CODE REVIEW

**Comment by xxEzri** [comment]
Lovakengj water color fix

Before:
image

After:
image

This is the northwestern Kourend ocean.

**Comment by xxEzri** [comment]
Lovakite Furnace light

Before:
image

After:
image

Fits in more with surrounding environment and gets rid of the dark shadows which look very bad on top of something which is supposed to be emitting light

**Comment by xxEzri** [comment]
Changed ground tiles around the Entrana glassblowing furnace building so that they're not spilling out inconsistently with the ground blending

Before:
image

After:
image

**Comment by xxEzri** [comment]
Varrock East Bank floor changes from @SirFancyBacon

image

**Comment by xxEzri** [comment]
Falador East Bank path fix from @SirFancyBacon

image

**Comment by xxEzri** [comment]
Light for cooking range found in Falador and probably elsewhere

Not super sold on this one because i couldn't position it where i wanted, but it looks okay i think

image

**Comment by xxEzri** [comment]
Evil Chicken shrine light

image

**Comment by xxEzri** [comment]
Fossil Island pics from @SirFancyBacon to come tomorrow

**Comment by xxEzri** [comment]
Some tuning on the GWD lighting and water - can't get this right due to shader/lighting issues i think but better IMO
image

image

**Comment by xxEzri** [comment]
image

Modified the ground blending on part of the path from Lumbridge to Draynor to get rid of a lot of artifacts on a particular area

**Comment by xxEzri** [comment]
New pulse lights for red/purple crystals under Mount Quidamortem (not sure if these are just for the shazien quest or exist elsewhere)

image

image

**Comment by xxEzri** [comment]
and "Glowing Carving"

image

**Comment by xxEzri** [comment]
Some accidental commits on there from Bacon (not supposed to be direct to pr branch), reverted them

Added lights for the fires during the last boss of Beneath Cursed Sands, for the two pyres in the ape atoll temple and for the entrance to the MM2 crash site cave

Changed water parameters on the upper level of the Ancient Cavern:
image
image

**Comment by aHooder** [comment]
Is this ready to go? It looks good, though I agree with Mark that the water looks slightly better in this screenshot, even though there's a bigger mismatch with the waterfall stuff.

image

**Comment by xxEzri** [comment]
https://streamable.com/6a3ipg

Ape Atoll sacrificial pyre - in the temple

**Comment by xxEzri** [comment]
https://streamable.com/i630k1

MM2 crash site cave skylight

**Comment by xxEzri** [comment]
https://streamable.com/y0uwfa

Lithkren lava lights

**Comment by xxEzri** [comment]
@aHooder everything pictured (exception for BCS boss fire) and good to go in here.

**Pull request merged**
